server:
  port: 9000
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web-api
    username: 'web-api'
    password:
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
application:
  jwt:
    secretKey: azer?/.§1234@abMyAp+°0/.?£µ%ANKJdkjvkjdizi+965'-"è&_à
    tokenPrefix: 'Bearer '
    tokenExpirationAfterDays: 1

file:
  uploadDir: '${user.home}/upload'
