version: '2'

services:
  db-gestion-facture:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=web-api
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ~/volumes/gestion/facturation/web-api/postgresql/:/var/lib/postgresql/data/
