name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  compile:
  
     runs-on: ubuntu-latest
     
     steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 11
       uses: actions/setup-java@v2
       with:
        java-version: '11'
        distribution: 'adopt'
     - name: compile project
       run: mvn clean compile
   
  # test:
  
  #    runs-on: ubuntu-latest
     
  #    steps:
  #    - uses: actions/checkout@v2
  #    - name: Set up JDK 11
  #      uses: actions/setup-java@v2
  #      with:
  #       java-version: '11'
  #       distribution: 'adopt'
  #    - name: run test
  #      run: mvn clean test
     
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file back.DockerFile --tag facture_back:$(date +%s)
  
  build-and-deploy:
 
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
         az vm run-command invoke -g myvm_group -n myvm --command-id RunShellScript --scripts "docker ps -a"
